version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: crud-api-redis

    mariadb:
      image: mariadb:10.1
      container_name: crud-api-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=pass4rd
        - MYSQL_DATABASE=crud
        - MYSQL_USER=crud
        - MYSQL_PASSWORD=pass4rd
      volumes:
        - ./db-dump:/docker-entrypoint-initdb.d

    webserver:
      image: nginx:alpine
      container_name: crud-api-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "9867:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: crud-api-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

